Ex2: Create a one-dimensional NumPy array of integers from 1 to 10 and specify its data type as float.

In [5]:
import numpy as np
array_float = np.arange(1, 11, dtype=float)
print(array_float)
array_float = np.linspace(1, 10, 10)
array_float

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Ex3: Create a one-dimensional NumPy array of the even numbers from 2 through 32 inclusive.

In [8]:
array_even=np.arange(2,33,2)
array_even
array_even=np.linspace(2,32,16,dtype=int)
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [10]:
array_even=np.array([number for number in range(2,33,2)])
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

Ex4: creates a 3x3 identity matrix using a NumPy function fill_diagonal(). 

In [12]:
identity_matrix=np.zeros((3,3))
identity_matrix
np.fill_diagonal(identity_matrix,1)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
identity_matrix=np.zeros((5,5))
np.fill_diagonal(identity_matrix,2)
identity_matrix

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

Ex5:

In [19]:
mixed_array1 = np.array([7, 2.4, "3"])
mixed_array1

array(['7', '2.4', '3'], dtype='<U32')

In [20]:
mixed_array2 = np.array([2, 5.1, 8.9])
mixed_array2

array([2. , 5.1, 8.9])

Ex6: Create a 2D array filled with arbitrary numbers, saved to a variable interesting_numbers and 
calculate the sum and average across each row and each column.

In [23]:
interesting_numbers=np.array([[1,2,3],[4,5,6]])
print(interesting_numbers)
sum_by_row = np.sum(interesting_numbers, axis=1)
print(sum_by_row)
sum_by_column = np.sum(interesting_numbers, axis=0) 
print(sum_by_column)
average_by_row = np.mean(interesting_numbers, axis=1)
print(average_by_row)
average_by_column = np.mean(interesting_numbers, axis=0) 
print(average_by_column)

[[1 2 3]
 [4 5 6]]
[ 6 15]
[5 7 9]
[2. 5.]
[2.5 3.5 4.5]


Ex:7 The following code creates a 4x4 array filled with arbitrary integers, slice a 2x2 section from it, 
reshape it into a 1x4 array, and then concatenate it with the 4x4 array.

In [24]:
array_4x4 = np.random.randint(1, 20, size=(4, 4))
array_4x4

array([[ 6, 18,  2,  7],
       [ 2,  5,  6, 17],
       [17,  9,  1,  1],
       [11, 13,  1,  5]], dtype=int32)

In [26]:
slice_array=array_4x4[:2,:2]
slice_array

array([[ 6, 18],
       [ 2,  5]], dtype=int32)

In [27]:
reshaped_section = slice_array.reshape(1, 4)
reshaped_section

array([[ 6, 18,  2,  5]], dtype=int32)

In [28]:
concatenated_array = np.concatenate((array_4x4, reshaped_section), axis=0)
concatenated_array

array([[ 6, 18,  2,  7],
       [ 2,  5,  6, 17],
       [17,  9,  1,  1],
       [11, 13,  1,  5],
       [ 6, 18,  2,  5]], dtype=int32)

Ex8: Look up the functions delete() and insert(), experiment with the examples to make sure you fully 
understand how they work. Then can you try to delete the second column from the array_4x4 in 
Exercise 7 and insert the provided new column in its place?

In [29]:
new_column = np.array([5,5,5,5]) 
modified_array = np.delete(array_4x4, 1, axis=1) 
final_array = np.insert(modified_array, 1, new_column, axis=1)
final_array

array([[ 6,  5,  2,  7],
       [ 2,  5,  6, 17],
       [17,  5,  1,  1],
       [11,  5,  1,  5]], dtype=int32)

Ex9: A class of 30 students have taken four programming tests, each graded out of 20 marks. You want 
to perform an analysis on the test results to understand the class’s performance. 
The test marks are stored in a 30x4 NumPy array, where each row represents a student and each 
column represents one of the four tests.

In [31]:
test_marks = np.array([[10, 16, 11,  3], 
       [ 5, 11, 12,  9], 
       [12, 10,  1, 13], 
       [18,  9,  7,  1], 
       [15,  4, 14, 12], 
       [16, 17,  7,  6], 
       [ 4, 11,  8,  2], 
       [16,  1, 12, 14],
       [ 6, 13,  5,  4], 
       [ 3, 15,  9,  5], 
       [18, 15, 14,  8], 
       [ 2,  6,  7, 18], 
       [ 3,  2, 14, 19], 
       [18, 19, 12,  1], 
       [ 8,  2,  8, 14], 
       [14, 13,  9, 10], 
       [ 5,  8,  6,  8], 
       [14, 11,  8, 18], 
       [15,  7, 19, 12], 
       [ 4, 16, 19,  4], 
       [13, 15, 10,  7], 
       [17,  7, 14,  7], 
       [ 9, 18, 15,  5], 
       [ 8, 10, 17,  4], 
       [ 9, 19, 17,  1], 
       [19,  5,  8,  6], 
       [17, 11, 18,  1], 
       [19, 18,  6, 19], 
       [ 7, 11, 16,  3], 
       [ 2,  8, 15,  6]])
test_marks

array([[10, 16, 11,  3],
       [ 5, 11, 12,  9],
       [12, 10,  1, 13],
       [18,  9,  7,  1],
       [15,  4, 14, 12],
       [16, 17,  7,  6],
       [ 4, 11,  8,  2],
       [16,  1, 12, 14],
       [ 6, 13,  5,  4],
       [ 3, 15,  9,  5],
       [18, 15, 14,  8],
       [ 2,  6,  7, 18],
       [ 3,  2, 14, 19],
       [18, 19, 12,  1],
       [ 8,  2,  8, 14],
       [14, 13,  9, 10],
       [ 5,  8,  6,  8],
       [14, 11,  8, 18],
       [15,  7, 19, 12],
       [ 4, 16, 19,  4],
       [13, 15, 10,  7],
       [17,  7, 14,  7],
       [ 9, 18, 15,  5],
       [ 8, 10, 17,  4],
       [ 9, 19, 17,  1],
       [19,  5,  8,  6],
       [17, 11, 18,  1],
       [19, 18,  6, 19],
       [ 7, 11, 16,  3],
       [ 2,  8, 15,  6]])

Task 1 
Calculate the mean, median, and standard deviation for the marks of each test.  

In [34]:
mean_marks=np.mean(test_marks,axis=0)
median_marks=np.median(test_marks,axis=0)
std_marks=np.std(test_marks,axis=0)
print("Average marks for each test",mean_marks)
print("Median mark for each test",median_marks)
print("Std mark for each test",std_marks)

Average marks for each test [10.86666667 10.93333333 11.26666667  8.        ]
Median mark for each test [11.  11.  11.5  6.5]
Std mark for each test [5.71392062 5.15062024 4.55289895 5.59166046]


Task 2 
Find the highest and lowest mark obtained in each test.

In [35]:
highest_mark=np.max(test_marks,axis=0)
lowest_mark=np.min(test_marks,axis=0)
print("Highest mark in each test",highest_mark)
print("Lowest mark in each test",lowest_mark)

Highest mark in each test [19 19 19 19]
Lowest mark in each test [2 1 1 1]


Task 3 
Identify the student with the highest total mark. 

In [36]:
total_marks=np.sum(test_marks,axis=1)
print("Total marks for each student",total_marks)


Total marks for each student [40 37 36 35 45 46 25 43 28 32 55 33 38 50 32 46 27 51 53 43 45 45 47 39
 46 38 47 62 37 31]


In [39]:
student_index=np.argmax(total_marks)
student_highest_mark=total_marks[student_index]
print("Highest total mark=",student_highest_mark)

Highest total mark= 62


Task 4 
The class has taken another test, graded out of 20. Add it to the array so that the array becomes 
30x5. 

In [41]:
test_5 = np.array([ 
    [ 1], [ 7], [ 3], [ 4], [ 1], [18], [18], [ 9], [ 3], [15], 
    [16], [ 1], [ 5], [13], [ 4], [ 7], [ 2], [ 9], [ 5], [11], 
    [16], [ 9], [ 4], [11], [17], [13], [19], [ 1], [ 9], [ 1] 
]) 
test_5

array([[ 1],
       [ 7],
       [ 3],
       [ 4],
       [ 1],
       [18],
       [18],
       [ 9],
       [ 3],
       [15],
       [16],
       [ 1],
       [ 5],
       [13],
       [ 4],
       [ 7],
       [ 2],
       [ 9],
       [ 5],
       [11],
       [16],
       [ 9],
       [ 4],
       [11],
       [17],
       [13],
       [19],
       [ 1],
       [ 9],
       [ 1]])

In [44]:
updated_mark=np.hstack((test_marks,test_5))
print("New Mark array=",updated_mark)

New Mark array= [[10 16 11  3  1]
 [ 5 11 12  9  7]
 [12 10  1 13  3]
 [18  9  7  1  4]
 [15  4 14 12  1]
 [16 17  7  6 18]
 [ 4 11  8  2 18]
 [16  1 12 14  9]
 [ 6 13  5  4  3]
 [ 3 15  9  5 15]
 [18 15 14  8 16]
 [ 2  6  7 18  1]
 [ 3  2 14 19  5]
 [18 19 12  1 13]
 [ 8  2  8 14  4]
 [14 13  9 10  7]
 [ 5  8  6  8  2]
 [14 11  8 18  9]
 [15  7 19 12  5]
 [ 4 16 19  4 11]
 [13 15 10  7 16]
 [17  7 14  7  9]
 [ 9 18 15  5  4]
 [ 8 10 17  4 11]
 [ 9 19 17  1 17]
 [19  5  8  6 13]
 [17 11 18  1 19]
 [19 18  6 19  1]
 [ 7 11 16  3  9]
 [ 2  8 15  6  1]]


Task 5 
You realise that there was an error in the marking of the third test. All students are to receive an 
additional 2 marks for that test, but the total should not exceed the maximum of 20 marks.  
Update the marks of the third test and ensure they are capped at 20 marks. 
Hint: Use a NumPy function where().  

In [46]:
updated_mark[:, 1] = np.where(updated_mark[:, 1] > 20, 20, updated_mark[:, 1]) + 2
updated_mark

array([[10, 18, 11,  3,  1],
       [ 5, 13, 12,  9,  7],
       [12, 12,  1, 13,  3],
       [18, 11,  7,  1,  4],
       [15,  6, 14, 12,  1],
       [16, 19,  7,  6, 18],
       [ 4, 13,  8,  2, 18],
       [16,  3, 12, 14,  9],
       [ 6, 15,  5,  4,  3],
       [ 3, 17,  9,  5, 15],
       [18, 17, 14,  8, 16],
       [ 2,  8,  7, 18,  1],
       [ 3,  4, 14, 19,  5],
       [18, 21, 12,  1, 13],
       [ 8,  4,  8, 14,  4],
       [14, 15,  9, 10,  7],
       [ 5, 10,  6,  8,  2],
       [14, 13,  8, 18,  9],
       [15,  9, 19, 12,  5],
       [ 4, 18, 19,  4, 11],
       [13, 17, 10,  7, 16],
       [17,  9, 14,  7,  9],
       [ 9, 20, 15,  5,  4],
       [ 8, 12, 17,  4, 11],
       [ 9, 21, 17,  1, 17],
       [19,  7,  8,  6, 13],
       [17, 13, 18,  1, 19],
       [19, 20,  6, 19,  1],
       [ 7, 13, 16,  3,  9],
       [ 2, 10, 15,  6,  1]])